# Generated by Django 5.2.6 on 2026-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(help_text='HTML content allowed')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Nehru Place IT Services', max_length=150)),
                ('tagline', models.CharField(default='Smart IT Solutions for Modern Business', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(default='+91 9876543210', max_length=50)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(default='info@nehruplaceitservices.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='919876543210', help_text='Number in international format without + sign, e.g. 919876543210', max_length=20)),
                ('address', models.TextField(default='Nehru Place, New Delhi, Delhi 110019')),
                ('google_map_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('about_text', models.TextField(blank=True, default='Nehru Place IT Services is your one-stop solution for IT products, custom website development, CCTV security installations, networking setup, and expert hardware repair.')),
                ('footer_text', models.TextField(blank=True, default='Empowering businesses with top-tier technology, responsive web applications, robust security systems, and reliable IT maintenance.')),
                ('default_meta_title', models.CharField(default='Nehru Place IT Services | IT Products, Web Dev, CCTV & Support', max_length=255)),
                ('default_meta_description', models.TextField(default='Leading provider of IT products, website development, CCTV installation, networking, and laptop repair services in Nehru Place.')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
