# Generated by Django 5.2.6 on 2026-09-27 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('camera_count', models.IntegerField(default=4)),
                ('camera_type', models.CharField(default='2MP HD Indoor/Outdoor Bullet', max_length=150)),
                ('dvr_nvr', models.CharField(default='4 Channel HD DVR', max_length=150)),
                ('storage', models.CharField(default='1 TB Hard Disk', max_length=150)),
                ('cable_meters', models.IntegerField(default=100)),
                ('installation_charge', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('wiring_charge', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['package_price'],
            },
        ),
        migrations.CreateModel(
            name='CCTVPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_price', models.DecimalField(decimal_places=2, default=2000.0, help_text='Base unit cost per camera', max_digits=10)),
                ('dvr_nvr_price', models.DecimalField(decimal_places=2, default=5000.0, help_text='DVR/NVR device cost', max_digits=10)),
                ('hdd_price', models.DecimalField(decimal_places=2, default=4000.0, help_text='Hard Disk Storage cost', max_digits=10)),
                ('power_supply_price', models.DecimalField(decimal_places=2, default=800.0, help_text='Power supply box cost', max_digits=10)),
                ('connector_price', models.DecimalField(decimal_places=2, default=300.0, help_text='BNC/DC connectors set', max_digits=10)),
                ('cable_price_per_meter', models.DecimalField(decimal_places=2, default=25.0, help_text='CCTV Cable cost per meter', max_digits=10)),
                ('installation_charge', models.DecimalField(decimal_places=2, default=2000.0, help_text='Standard installation labor charge', max_digits=10)),
                ('wiring_charge_per_meter', models.DecimalField(decimal_places=2, default=15.0, help_text='Wiring labor charge per meter', max_digits=10)),
                ('configuration_charge', models.DecimalField(decimal_places=2, default=1000.0, help_text='Network & Mobile App setup charge', max_digits=10)),
                ('maintenance_charge', models.DecimalField(decimal_places=2, default=1500.0, help_text='Optional AMC / Maintenance charge', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CCTV Pricing Configuration',
                'verbose_name_plural': 'CCTV Pricing Configuration',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='bi-tools', help_text='Bootstrap icon class name, e.g. bi-laptop, bi-camera-video, bi-globe', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_unit', models.CharField(default='per project', help_text='e.g. per project, per camera, per device', max_length=50)),
                ('delivery_time', models.CharField(default='3-5 Days', help_text='e.g. Same Day, 3-5 Days', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('features', models.TextField(help_text='Enter features separated by line breaks')),
                ('delivery_days', models.CharField(blank=True, default='', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
    ]
