# Generated by Django 5.2.6 on 2026-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='comparison_guide_html',
            field=models.TextField(blank=True, default='', help_text='HTML table comparing service tiers, SLAs, and deliverables'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='learning_video_description',
            field=models.TextField(blank=True, default='', help_text='Short description of what is explained in this service video'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='learning_video_title',
            field=models.CharField(blank=True, default='', help_text='e.g. CCTV Installation & Network Configuration Demo', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='learning_video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video link for service tutorial/demo'),
        ),
    ]
