# Generated by Django 5.2.6 on 2026-09-27 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='enquiries/attachments/')),
                ('source', models.CharField(choices=[('WEBSITE', 'General Website'), ('PRODUCT', 'Product Page'), ('SERVICE', 'Service Page'), ('CCTV_CALCULATOR', 'CCTV Calculator'), ('CONTACT', 'Contact Page'), ('WHATSAPP', 'WhatsApp Link')], default='WEBSITE', max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=30)),
                ('calculation_details', models.TextField(blank=True, default='', help_text='Stored breakdown for CCTV calculator enquiries')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='products.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='services.service')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='enquiries_e_phone_86203a_idx'), models.Index(fields=['status'], name='enquiries_e_status_a2aded_idx'), models.Index(fields=['created_at'], name='enquiries_e_created_5892d9_idx')],
            },
        ),
    ]
