# Generated by Django 5.2.6 on 2026-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='comparison_guide_html',
            field=models.TextField(blank=True, default='', help_text='HTML or table matrix comparing specifications, models, and features in this category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='learning_video_description',
            field=models.TextField(blank=True, default='', help_text='Short overview of what is explained in this learning video'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='learning_video_title',
            field=models.CharField(blank=True, default='', help_text='e.g. CCTV Camera & DVR Selection Guide', max_length=255),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='learning_video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video link (e.g., https://www.youtube.com/watch?v=VIDEO_ID)'),
        ),
    ]
