# Generated by Django 5.2.6 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_comparison_guide_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='learning_video_description',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='learning_video_title',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='learning_video_url',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='comparison_guide_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='comparison_guide_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
