# Generated by Django 5.2.6 on 2026-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productcategory_learning_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video link for product tutorial/demo', max_length=500),
        ),
    ]
