# Generated by Django 5.2.6 on 2026-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='view_type',
            field=models.CharField(choices=[('FRONT', 'Front View'), ('BACK', 'Back / Rear View'), ('SIDE', 'Side View'), ('TOP', 'Top / Bottom View'), ('PORTS', 'Ports & Connectors'), ('UNBOXING', 'Package / Unboxing'), ('DIMENSION', 'Dimensions / Diagram'), ('IN_USE', 'Installed / In-Use'), ('OTHER', 'General Photo')], default='FRONT', help_text='Select photo view angle/type (e.g. Front View, Back View, Ports)', max_length=30),
        ),
    ]
